"use client";

import * as React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { bookSchema, type BookValues } from "@/lib/validations/book";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/Label";
import { Button } from "@/components/ui/Button";
import { UploadCloud, Loader2, X, Image as ImageIcon, Sparkles, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { FadeIn } from "@/components/animations/FadeIn";

interface BookFormProps {
  initialData?: BookValues & { status?: string };
  isEditing?: boolean;
}

export const BookForm = ({ initialData, isEditing = false }: BookFormProps) => {
  const [isLoading, setIsLoading] = React.useState(false);
  const [images, setImages] = React.useState<string[]>([]);
  const [isGeneratingDesc, setIsGeneratingDesc] = React.useState(false);
  
  const router = useRouter();

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<BookValues>({
    resolver: zodResolver(bookSchema),
    defaultValues: initialData || {
      title: "",
      author: "",
      isbn: "",
      description: "",
      condition: undefined,
      category: "",
      price: "",
    },
  });

  // eslint-disable-next-line react-hooks/incompatible-library
  const watchTitle = watch("title");
  // eslint-disable-next-line react-hooks/incompatible-library
  const watchCondition = watch("condition");

  const onSubmit = async (_data: BookValues) => {
    setIsLoading(true);
    await new Promise((resolve) => setTimeout(resolve, 1500));
    setIsLoading(false);
    toast.success(isEditing ? "Book updated successfully! (Mock)" : "Book listed successfully! (Mock)");
    router.push("/dashboard/books");
  };

  const handleImageMock = () => {
    if (images.length >= 3) {
      toast.error("Maximum 3 images allowed");
      return;
    }
    setImages([...images, `mock-image-${Date.now()}`]);
  };

  const removeImageMock = (index: number) => {
    setImages(images.filter((_, i) => i !== index));
  };

  // AI Features
  const generateDescription = () => {
    if (!watchTitle) {
      toast.error("Please enter a title first to generate a description.");
      return;
    }
    setIsGeneratingDesc(true);
    setTimeout(() => {
      setValue("description", `This is a high-quality copy of ${watchTitle}. It has been well-maintained and is perfect for students looking to excel in their coursework. Contains complete, unabridged chapters and standard index.`);
      setIsGeneratingDesc(false);
      toast.success("Description generated by AI!");
    }, 1500);
  };

  const applySuggestedPrice = () => {
    setValue("price", "450");
    toast.success("AI Suggested price applied.");
  };

  const isDuplicateDetected = watchTitle.toLowerCase().includes("algorithm");

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 relative">
      
      {/* Image Upload Mockup */}
      <FadeIn delay={0.1}>
        <div className="space-y-4">
          <div>
            <h3 className="text-lg font-bold">Book Images</h3>
            <p className="text-sm text-muted-foreground">Upload up to 3 high-quality images of the book (Max 5MB each).</p>
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {images.length < 3 && (
              <button 
                type="button"
                onClick={handleImageMock}
                className="h-40 rounded-2xl border-2 border-dashed border-white/20 hover:border-primary/50 bg-white/5 hover:bg-primary/5 flex flex-col items-center justify-center gap-2 transition-all group"
              >
                <div className="w-12 h-12 rounded-full bg-background flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                  <UploadCloud className="w-6 h-6 text-muted-foreground group-hover:text-primary transition-colors" />
                </div>
                <span className="text-sm font-medium text-muted-foreground group-hover:text-foreground">Click to add image</span>
              </button>
            )}

            {images.map((img, idx) => (
              <div key={img} className="h-40 rounded-2xl bg-white/10 border border-white/10 relative overflow-hidden flex items-center justify-center group">
                <ImageIcon className="w-10 h-10 text-muted-foreground/50" />
                <button
                  type="button"
                  onClick={() => removeImageMock(idx)}
                  className="absolute top-2 right-2 p-1.5 rounded-full bg-red-500/80 text-white opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-500"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        </div>
      </FadeIn>

      <hr className="border-white/10" />

      {/* Book Details */}
      <FadeIn delay={0.2} className="space-y-6">
        <div>
          <h3 className="text-lg font-bold">Book Details</h3>
          <p className="text-sm text-muted-foreground">Provide information to help others find your book.</p>
        </div>

        {isDuplicateDetected && (
          <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-start gap-3 animate-in fade-in slide-in-from-top-2">
            <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-bold text-amber-500">AI Duplicate Detection</p>
              <p className="text-sm text-amber-500/80 mt-1">We detected 3 similar listings for this textbook. Consider offering a direct exchange or lowering your price slightly to stand out.</p>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="title">Book Title *</Label>
            <Input id="title" placeholder="e.g. Introduction to Algorithms" {...register("title")} />
            {errors.title && <p className="text-xs text-red-500">{errors.title.message}</p>}
          </div>
          <div className="space-y-2">
            <Label htmlFor="author">Author *</Label>
            <Input id="author" placeholder="e.g. Thomas H. Cormen" {...register("author")} />
            {errors.author && <p className="text-xs text-red-500">{errors.author.message}</p>}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="category">Category *</Label>
            <select 
              id="category"
              className="flex h-12 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-foreground shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary/50 appearance-none"
              {...register("category")}
            >
              <option value="" className="bg-background">Select a category</option>
              <option value="cs" className="bg-background">Computer Science</option>
              <option value="engineering" className="bg-background">Engineering</option>
              <option value="physics" className="bg-background">Physics</option>
            </select>
            {errors.category && <p className="text-xs text-red-500">{errors.category.message}</p>}
          </div>
          <div className="space-y-2">
            <Label htmlFor="condition">Condition *</Label>
            <select 
              id="condition"
              className="flex h-12 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-foreground shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary/50 appearance-none"
              {...register("condition")}
            >
              <option value="" className="bg-background">Select condition</option>
              <option value="NEW" className="bg-background">New</option>
              <option value="LIKE_NEW" className="bg-background">Like New</option>
              <option value="GOOD" className="bg-background">Good</option>
              <option value="POOR" className="bg-background">Poor</option>
            </select>
            {errors.condition && <p className="text-xs text-red-500">{errors.condition.message}</p>}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="isbn">ISBN (Optional)</Label>
            <Input id="isbn" placeholder="e.g. 978-0262033848" {...register("isbn")} />
            {errors.isbn && <p className="text-xs text-red-500">{errors.isbn.message}</p>}
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="price">Price in ₹ (Optional)</Label>
              {watchCondition && (
                <button type="button" onClick={applySuggestedPrice} className="text-xs font-bold text-primary flex items-center hover:text-primary/80 transition-colors">
                  <Sparkles className="w-3 h-3 mr-1" /> AI Suggest: ₹450
                </button>
              )}
            </div>
            <Input id="price" type="number" placeholder="Leave empty for direct exchange" {...register("price")} />
            {errors.price && <p className="text-xs text-red-500">{errors.price.message}</p>}
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label htmlFor="description">Description *</Label>
            <button 
              type="button" 
              onClick={generateDescription}
              disabled={isGeneratingDesc}
              className="text-xs font-bold text-primary flex items-center hover:text-primary/80 transition-colors disabled:opacity-50"
            >
              {isGeneratingDesc ? <Loader2 className="w-3 h-3 mr-1 animate-spin" /> : <Sparkles className="w-3 h-3 mr-1" />}
              {isGeneratingDesc ? "Generating..." : "AI Generate"}
            </button>
          </div>
          <textarea
            id="description"
            rows={4}
            className="flex w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-foreground shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary/50 resize-none"
            placeholder="Describe the condition, edition, and any included materials..."
            {...register("description")}
          />
          {errors.description && <p className="text-xs text-red-500">{errors.description.message}</p>}
        </div>
      </FadeIn>

      <hr className="border-white/10" />

      {/* Actions */}
      <div className="flex items-center justify-end gap-4">
        <Button type="button" variant="ghost" onClick={() => router.back()} disabled={isLoading}>
          Cancel
        </Button>
        <Button type="submit" variant="primary" className="w-40 font-bold" disabled={isLoading}>
          {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : (isEditing ? "Save Changes" : "List Book")}
        </Button>
      </div>

    </form>
  );
};
